### ISSUE TITLE
ElasticsearchのGUIアプリを作る

### ISSUE THREAD

**Issue by hirokisan** [unfunctionals/unfunctionals.com#20]
ElasticsearchのGUIアプリなかなか良さげなものが見つからない。

GUIアプリに求める機能を明確にした上でGUIアプリを作ってみたい。

デスクトップアプリをイメージしている。

接続先を登録して、index一覧からindexを指定して、mapping定義を見ながら、queryを書いて投げられたら良いな。

このissueでは企画を詰めて、専用のrepositoryを用意するところまで。repositoryを作成したら、そちらで作業を進める。

**Comment by yuki777** [comment]
awesome + $keywordでググると良いよ

https://github.com/dzharii/awesome-elasticsearch

**Comment by yuki777** [comment]
https://github.com/appbaseio/dejavu

githubで一番人気

**Comment by hirokisan** [comment]
https://github.com/unfunctionals/unfunctionals.com/issues/20#issuecomment-733864361

イメージは本当にそういう感じ

**Comment by hirokisan** [comment]
https://github.com/appbaseio/dejavu#cross-origin-resource-sharing-cors

cors設定したくない。デスクトップアプリなら設定せずに済むのでは？（済むかどうかはわかっていない）

docker立ち上げたくない。デスクトップアプリが良い。

デスクトップアプリ作りたい。笑

**Comment by yuki777** [comment]
> デスクトップアプリ作りたい。笑

これはわかる

**Comment by hirokisan** [comment]
📝 これでデスクトップアプリを作る

- Flutter https://flutter.dev/desktop https://github.com/flutter/flutter
- Electron https://github.com/electron/electron

スター数とかコミット頻度とか、いろいろ考慮するとこの2択で良さそう。

**Comment by hirokisan** [comment]
escaptain

船長のように地図を見て、世界を見て、指令を出す。

**Comment by hirokisan** [comment]
https://github.com/unfunctionals/escaptain

リポジトリ用意するところまで。
