### ISSUE TITLE
デプロイ完了後にslack通知する

### ISSUE THREAD

**Issue by hirokisan** [unfunctionals/unfunctionals.com#5]
from: https://github.com/unfunctionals/unfunctionals.com/pull/4#pullrequestreview-446730515

github actionsでdeployした際に、slack通知してほしい。

**Comment by yuki777** [comment]
https://github.com/marketplace/actions/slack-incoming-webhook
https://spinners.work/posts/github-actions-context/

これを入れてみます

**Comment by hirokisan** [comment]
📝 こういうのもあります
https://github.com/8398a7/action-slack

**Comment by yuki777** [comment]
> https://github.com/8398a7/action-slack

こっちにしてみようか

**Comment by yuki777** [comment]
https://spinners.work/posts/github-actions-context/

```
Action独自のパラメータでなくSlackが定義しているMessage payloadsのフィールドをそのまま指定したい

GitHubで変更差分を見るためのURLを追加したりとか、お好みでカスタムしたい
```

これができるならusers/stars多い方のaction使いたいね

**Comment by yuki777** [comment]
Slack側でincoming-webhook設定した
https://unfunctionals.slack.com/apps/A0F7XDUAZ--incoming-webhook-?next_id=0

GithubでSecret設定した
https://github.com/unfunctionals/unfunctionals.com/settings/secrets
